# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test4DailyPull():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_4DailyPull(self):
    self.driver.get("https://www.kwikrewards.com/kwik-rewards/games/pull-tab/4916/play-free")
    self.driver.set_window_size(1792, 1095)
    self.driver.find_element(By.CSS_SELECTOR, ".cta").click()
    self.driver.find_element(By.CSS_SELECTOR, ".back-to-game").click()
  
