# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test1Login():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_1Login(self):
    self.driver.get("https://www.kwikrewards.com/")
    self.vars["error"] = len(self.driver.find_elements(By.XPATH, "//span[contains(.,\'Logout\')]"))
    print("error {}".format(self.vars["error"]))
    if self.driver.execute_script("return (arguments[0]>0)", self.vars["error"]):
      print("\"logged in already")
      elements = self.driver.find_elements(By.XPATH, "//span[contains(.,\'Logout\')]")
      assert len(elements) > 0
    else:
      self.driver.set_window_size(1792, 1095)
      self.driver.find_element(By.LINK_TEXT, "Log In").click()
      self.driver.find_element(By.ID, "Password").send_keys("Password")
      self.driver.find_element(By.ID, "Username").send_keys("Email")
      self.driver.find_element(By.NAME, "button").click()
      self.driver.find_element(By.CSS_SELECTOR, "main").click()
      self.driver.find_element(By.CSS_SELECTOR, ".navigation-item:nth-child(2)").click()
      print("\"now logged in\"")
  
