# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test3bonusTabv2Basic():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_3bonusTabv2Basic(self):
    for i in range(0, 20):
      self.driver.get("https://www.kwikrewards.com/kwik-rewards/games/pull-tab/4916/play-bonus")
      self.driver.set_window_size(1792, 1095)
      self.driver.find_element(By.CSS_SELECTOR, ".cta").click()
      self.driver.find_element(By.CSS_SELECTOR, ".back-to-game").click()
      self.vars["entries"] = self.driver.find_element(By.CSS_SELECTOR, ".value").text
      self.vars["ticketsleft"] = self.driver.find_element(By.CSS_SELECTOR, ".bonus-ticket > .title").text
      print("{} , Entries: ${entries}".format(self.vars["ticketsleft"]))
      time.sleep(16)
  
