# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test2AdditionalEntries():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_2AdditionalEntries(self):
    self.vars["error"] = "0"
    print("error {}".format(self.vars["error"]))
    for i in range(0, 20):
      print("error {}".format(self.vars["error"]))
      self.driver.get("https://www.kwiktrip.com/game-alternate-means-of-entry")
      self.driver.set_window_size(1792, 1095)
      self.driver.find_element(By.CSS_SELECTOR, ".frm_fields_container").click()
      self.driver.find_element(By.ID, "field_wwtp30343e5988ff7").click()
      self.driver.find_element(By.ID, "field_wwtp30343e5988ff7").send_keys("First")
      self.driver.find_element(By.ID, "field_oag1ms3b6e9660031").send_keys("Last")
      self.driver.find_element(By.ID, "field_dob").click()
      self.driver.find_element(By.ID, "field_dob").send_keys("1/30/2000")
      self.driver.find_element(By.ID, "field_wmy4z_line1").send_keys("Address")
      self.driver.find_element(By.ID, "field_wmy4z_city").send_keys("City")
      dropdown = self.driver.find_element(By.ID, "field_wmy4z_state")
      dropdown.find_element(By.XPATH, "//option[. = 'Washington']").click()
      dropdown = self.driver.find_element(By.ID, "field_wmy4z_state")
      dropdown.find_element(By.XPATH, "//option[. = 'Wisconsin']").click()
      self.driver.find_element(By.ID, "field_wmy4z_zip").send_keys("Zip")
      self.driver.find_element(By.ID, "field_fulei").send_keys("Phone")
      self.driver.find_element(By.ID, "field_xnkv8k31bc11424c0").send_keys("Emailaddress")
      self.driver.find_element(By.ID, "field_loyalty_number").click()
      self.driver.find_element(By.ID, "field_loyalty_number").send_keys("1231231231")
      self.driver.find_element(By.CSS_SELECTOR, "label > span:nth-child(2)").click()
      self.driver.find_element(By.CSS_SELECTOR, ".frm_button_submit").click()
  
